services:
  base-frontend:
    build: ./
    image: base-frontend
    working_dir: /usr/src/app/
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:3000
    command: npm run dev
